name: export-linux
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paulloz/godot-action@v1
        with:
          version: 3.5
          mono: true
      - run: |
          godot --version
          godot --export "Linux/X11" "./export"
          


      
